### ISSUE TITLE
Does not work for Concrete5 8.5

### ISSUE THREAD

**Issue by ok-ttc** [nikolai-nikolajevic/concrete5-slick-carousel#1]
When trying to install it says "Unable to install slick_carousel. Please check that this package has been updated for 5.7."

**Comment by nikolai-nikolajevic** [comment]
> When trying to install it says "Unable to install slick_carousel. Please check that this package has been updated for 5.7."

It should work when you rename the folder to "slick_carousel". I will add this to the readme :)
